image: docker:stable
services:
    - docker:dind
stages:
    - build
    - deploy
variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
build_image:
    stage: build
    variables:
        DOCKER_HOST: tcp://docker:2375
    script:
        - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
        - docker build --pull -t $IMAGE_TAG -f dockerfile .
        - docker push $IMAGE_TAG
    only:
        - master
ec2:
    stage: deploy
    image: patitogordito/debian-ssh
    before_script:
        - |
            function ssh_config() {
                mkdir ~/.ssh
                cp $SSH_PRIVATE_KEY ~/.ssh/id_rsa
                chmod 600 ~/.ssh/id_rsa
                cp $SSH_CONFIG ~/.ssh/config
            }
    script:
        - ssh_config
        - ssh ec2 "docker stop app" || true
        - ssh ec2 "docker rm app" || true
        - ssh ec2 "docker run -dti -p 80:3000 --name app --network p-manager $IMAGE_TAG"
    only:
        - master